sudo: true
dist: trusty
env:
  - TEST_DIR=logstash-kafka-avro
install:
  - "curl http://files.zerogw.com/vagga/vagga-install-testing.sh | sh"
  - "echo ubuntu-mirror: http://mirrors.us.kernel.org/ubuntu/ > ~/.vagga.yaml"
  - "echo alpine-mirror: http://mirrors.gigenet.com/alpinelinux/ >> ~/.vagga.yaml"
script: cd $TEST_DIR && vagga test

